version: 2

models:
  - name: int_monthly
    description: "Monthly aggregated weather data per province. Temperature averaged, rainfall and sunshine summed, wind speed max."
    columns:
      - name: province
        tests:
          - not_null
      - name: year
        tests:
          - not_null
      - name: month
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]
                quote: False