volumes:
  kestra-data:

services:
  kestra:
    image: kestra/kestra:latest
    command: server local
    user: "root"
    ports:
      - "8080:8080"
    environment:
      KESTRA_CONFIGURATION: |
        kestra:
          variables:
            gcp_project_id: "air-quality-data-pipeline"
      GOOGLE_APPLICATION_CREDENTIALS: /secrets/sa-key.json
      OPENAQ_API_KEY: ${OPENAQ_API_KEY}
    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./service-account-key.json:/secrets/sa-key.json